### ISSUE TITLE
Bug. when cursor is on the first character of input and press enter it is copying all the text to the next node

### ISSUE THREAD

**Issue by letmewearshoes** [irshuLx/Android-WYSIWYG-Editor#83]

**Comment by ArmanYvz** [comment]
I'm using this editor in my project and having the same issue as yours. Why did you close this issue? Is there any solution to this?

**Comment by letmewearshoes** [comment]
> I'm using this editor in my project and having the same issue as yours. Why did you close this issue? Is there any solution to this?

I forked this library and fixed by myself

**Comment by ArmanYvz** [comment]
Can you provide a link for your fix fork? Fork is most probably private, i couldn't find it in your profile. If possible, could you send a invitation link to fork? This issue persists, we're using this editor in a Uni project, so it's important for us to fix it.

**Comment by ArmanYvz** [comment]
nevermind, i fixed it. thanks.
